name: bicep
channels:
    - bioconda
    - conda-forge
    - defaults
dependencies:
    - cyvcf2=0.11.5
    - joblib=1.1.1
    - matplotlib=3.3.4
    - numpy=1.19.5
    - pandas=0.23.4
    - scikit_learn=0.24.2
    - scipy=1.5.4
    - statsmodels=0.12.2
